version: '2'

services:
    db:
        image: mysql
        container_name: masterstream2-db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
    redis:
        image: redis:alpine
        container_name: masterstream2-redis
        ports:
            - 6379:6379
    php:
        build: php7-fpm
        container_name: masterstream2-php
        ports:
            - 9001:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - /home/matt/salestreamsoft/masterstream2/masterstream-UI:/var/www/masterstream
            - ./logs/masterstream:/var/www/masterstream/app/logs
    nginx:
        build: nginx
        container_name: masterstream2-nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        container_name: masterstream2-elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
